spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: carlosdavidravi@gmail.com
    password: ngvxuxktsgfjtvmq
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: Cdavid2004


  jpa:
    hibernate:
      ddl-auto: update  # or create-drop for dev
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
